# Generated by Django 3.1.3 on 2020-11-07 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Korisnik',
            fields=[
                ('korisnikid', models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('korisnickoime', models.CharField(max_length=20, unique=True)),
                ('lozinka', models.CharField(max_length=20)),
                ('razinaautoriteta', models.IntegerField()),
                ('adresa', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('rodendan', models.DateField(blank=True, default=None, null=True)),
                ('datumregistracije', models.DateField(blank=True, default=None, null=True)),
                ('adresaprivatna', models.BooleanField(blank=True, default=False, null=True)),
                ('rodendanprivatan', models.BooleanField(blank=True, default=False, null=True)),
                ('datumregistracijeprivatan', models.BooleanField(blank=True, default=False, null=True)),
                ('ime', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('prezime', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('dozvoljenpristup', models.BooleanField(blank=True, default=None, null=True)),
                ('brojracuna', models.CharField(blank=True, default=None, max_length=21, null=True)),
            ],
            options={
                'db_table': 'korisnik',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Maketa',
            fields=[
                ('maketaid', models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False)),
                ('dimenzije', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'maketa',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Materijal',
            fields=[
                ('materijalid', models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False)),
                ('ime', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'materijal',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('mediaid', models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False)),
                ('vrstamedije', models.CharField(max_length=20)),
                ('putdodatoteke', models.TextField(unique=True)),
            ],
            options={
                'db_table': 'media',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Transakcija',
            fields=[
                ('transakcijaid', models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False)),
                ('ime', models.CharField(max_length=100)),
                ('prezime', models.CharField(max_length=100)),
                ('adresa', models.CharField(max_length=100)),
                ('brojracuna', models.CharField(max_length=21)),
                ('ukupaniznos', models.FloatField()),
            ],
            options={
                'db_table': 'transakcija',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('temaid', models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False)),
                ('ime', models.CharField(max_length=100)),
                ('teksttemeid', models.ForeignKey(db_column='teksttemeid', on_delete=django.db.models.deletion.DO_NOTHING, to='maketashop.media')),
            ],
            options={
                'db_table': 'tema',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Prica',
            fields=[
                ('pricaid', models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False)),
                ('naslovprice', models.CharField(default='Priča', max_length=100)),
                ('datumprice', models.DateField(blank=True, default='1900-01-01')),
                ('brojlajkova', models.IntegerField(blank=True, default=0)),
                ('brojdislajkova', models.IntegerField(blank=True, default=0)),
                ('objavljena', models.BooleanField(blank=True, default=False)),
                ('maketaprodana', models.BooleanField(blank=True, default=False)),
                ('autorid', models.ForeignKey(db_column='autorid', on_delete=django.db.models.deletion.DO_NOTHING, related_name='autorid', to='maketashop.korisnik')),
                ('glavnaslikapriceid', models.ForeignKey(db_column='glavnaslikapriceid', on_delete=django.db.models.deletion.DO_NOTHING, related_name='glavnaslikaprice', to='maketashop.media')),
                ('maketaid', models.ForeignKey(db_column='maketaid', on_delete=django.db.models.deletion.DO_NOTHING, to='maketashop.maketa')),
                ('predloziopricuid', models.ForeignKey(db_column='predloziopricuid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='predloziopricuid', to='maketashop.korisnik')),
                ('tekstpriceid', models.ForeignKey(db_column='tekstpriceid', on_delete=django.db.models.deletion.DO_NOTHING, related_name='tekstprice', to='maketashop.media')),
            ],
            options={
                'db_table': 'prica',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='maketa',
            name='mediaid',
            field=models.ForeignKey(db_column='mediaid', on_delete=django.db.models.deletion.DO_NOTHING, to='maketashop.media'),
        ),
        migrations.AddField(
            model_name='korisnik',
            name='profilnaid',
            field=models.ForeignKey(blank=True, db_column='profilnaid', default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='maketashop.media'),
        ),
        migrations.CreateModel(
            name='Komentar',
            fields=[
                ('komentarid', models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False)),
                ('sadrzaj', models.CharField(max_length=300)),
                ('korisnikid', models.ForeignKey(db_column='korisnikid', on_delete=django.db.models.deletion.DO_NOTHING, to='maketashop.korisnik')),
                ('pricaid', models.ForeignKey(db_column='pricaid', on_delete=django.db.models.deletion.DO_NOTHING, to='maketashop.prica')),
            ],
            options={
                'db_table': 'komentar',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Custommaketa',
            fields=[
                ('custommaketaid', models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False)),
                ('datumotvaranjazahtjeva', models.DateField()),
                ('datumzatvaranjadatuma', models.DateField()),
                ('ponudenacijena', models.FloatField(blank=True, default=None, null=True)),
                ('prihvaceno', models.BooleanField(blank=True, default=False, null=True)),
                ('korisnikid', models.ForeignKey(db_column='korisnikid', on_delete=django.db.models.deletion.DO_NOTHING, to='maketashop.korisnik')),
                ('tekstzahtjevaid', models.ForeignKey(db_column='tekstzahtjevaid', on_delete=django.db.models.deletion.DO_NOTHING, to='maketashop.media')),
            ],
            options={
                'db_table': 'custommaketa',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Napravljenaod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cijena', models.FloatField()),
                ('maketaid', models.ForeignKey(db_column='maketaid', on_delete=django.db.models.deletion.DO_NOTHING, to='maketashop.maketa')),
                ('materijalid', models.ForeignKey(db_column='materijalid', on_delete=django.db.models.deletion.DO_NOTHING, to='maketashop.materijal')),
            ],
            options={
                'db_table': 'napravljenaod',
                'managed': True,
                'unique_together': {('maketaid', 'materijalid')},
            },
        ),
        migrations.CreateModel(
            name='Multimedijaprice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poredakuprici', models.IntegerField()),
                ('mediaid', models.ForeignKey(db_column='mediaid', on_delete=django.db.models.deletion.DO_NOTHING, to='maketashop.media')),
                ('pricaid', models.ForeignKey(db_column='pricaid', on_delete=django.db.models.deletion.DO_NOTHING, to='maketashop.prica')),
            ],
            options={
                'db_table': 'multimedijaprice',
                'managed': True,
                'unique_together': {('pricaid', 'mediaid')},
            },
        ),
        migrations.CreateModel(
            name='Maketakupljena',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kolicina', models.IntegerField(default=0)),
                ('maketaid', models.ForeignKey(db_column='maketaid', on_delete=django.db.models.deletion.DO_NOTHING, to='maketashop.maketa')),
                ('materijalid', models.ForeignKey(db_column='materijalid', on_delete=django.db.models.deletion.DO_NOTHING, to='maketashop.materijal')),
                ('transakcijaid', models.ForeignKey(db_column='transakcijaid', on_delete=django.db.models.deletion.DO_NOTHING, to='maketashop.transakcija')),
            ],
            options={
                'db_table': 'maketakupljena',
                'managed': True,
                'unique_together': {('transakcijaid', 'maketaid', 'materijalid')},
            },
        ),
    ]
